version: "3.9"
services:
  database:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: psql -U postgres -q -d postgres -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@database/postgres
      - ITERATION_TIME_SECS=${ITERATION_TIME_SECS}
      - FANTOM_RPC_URL=${FANTOM_RPC_URL}
      - BASE_RPC_URL=${BASE_RPC_URL}
      - CANTO_RPC_URL=${CANTO_RPC_URL}

volumes:
  db-data:
