//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bribes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub bribe_address: String,
    #[sea_orm(column_type = "Double")]
    pub reward_amount: f64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub token_address: String,
    pub token: Json,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub plugin_address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assets::Entity",
        from = "Column::TokenAddress",
        to = "super::assets::Column::Address",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Assets,
    #[sea_orm(
        belongs_to = "super::plugins::Entity",
        from = "Column::PluginAddress",
        to = "super::plugins::Column::Address",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Plugins,
}

impl Related<super::assets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assets.def()
    }
}

impl Related<super::plugins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plugins.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
